server:
  port: 7026

spring:
  application:
    name: service-order
  cloud:
    sentinel:
      transport:
        dashboard: localhost:9090
        port: 8719

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.niu.security.orderapi: debug

security:
  oauth2:
    client:
      client-id: orderService
      client-secret: 123456
    resource:
      jwt:
        # 配置令牌公钥地址
        key-uri: http://auth.niu.com:7046/oauth/token_key

sentinel:
  zookeeper:
    address: 127.0.0.1:2181
    path: /sentinel_rule_config

