server:
  port: 7086

spring:
  application:
    name: service-login

logging:
  config: classpath:logback.xml
  level:
    root: info
    com.niu.security.orderapi: debug

zuul:
  routes:
    api:
      url: http://gateway.niu.com:7056
  sensitive-headers: