security:
  oauth2:
    client:
      client-id: merryyou
      client-secret: merryyou
server:
#  session:
#    timeout: 60
  port: 9090
spring:
#  session:
#    store-type: redis
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
logging:
  level:
    org.springframework: debug
merryyou:
  security:
    oauth2:
      storeType: jwt
      jwtSigningKey: merryyou
      clients[0]:
        clientId: merryyou
        clientSecret: merryyou
      clients[1]:
              clientId: merryyou1
              clientSecret: merryyou1
