server:
  port: 7016

spring:
  application:
    name: service-price

logging:
#  config: classpath:logback.xml
  level:
    root: info
    com.niu.security.priceapi: debug

security:
  oauth2:
    client:
      client-id: orderService
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://auth.niu.com:7046/oauth/token_key